'use strict';

/**
 * @param {object} result  FunMeter.run()이 반환한 결과 객체
 * @returns {string}       GFM Markdown 문자열
 */
function toMarkdown(result) {
  const { name, runs, zone, emoji, advice, mean, median, stddev,
          p25, p75, p90, p95, timeoutRate, scoreMean, scoreMax,
          levelStats, histogram } = result;

  const histLines = histogram.map(function(h) {
    var label = (h.from.toFixed(1) + '~' + h.to.toFixed(1) + 's').padEnd(13);
    var bar = '';
    for (var i = 0; i < h.bar.length; i++) bar += '\u2588';
    bar = bar.padEnd(15);
    return '  ' + label + ' ' + bar + ' (' + h.count + ')';
  }).join('\n');

  const levelSection = levelStats ? [
    '',
    '## 레벨',
    '',
    '| 항목 | 값 |',
    '|------|----|',
    '| 평균 | ' + levelStats.mean.toFixed(1) + ' |',
    '| 중앙값 | ' + levelStats.median.toFixed(1) + ' |',
    '| 최고 | ' + levelStats.max + ' |',
    '| p25 / p75 | ' + levelStats.p25.toFixed(1) + ' / ' + levelStats.p75.toFixed(1) + ' |',
  ].join('\n') : '';

  const deathPatternSection = result.deathPattern ? [
    '',
    '## 사망 패턴',
    '',
    '- 왜도: ' + result.deathPattern.skewness,
    '- 첨도: ' + result.deathPattern.kurtosis,
    '- 분포: ' + result.deathPattern.cluster,
  ].join('\n') + '\n' : '';

  const suggestionsSection = (result.suggestions?.length > 0)
    ? '## 제안\n\n' + result.suggestions.map(function(s) { return '- ' + s; }).join('\n') + '\n\n'
    : '';

  const lines = [
    '## ' + emoji + ' ' + name + ' — Fun Meter 리포트 (' + zone + ')',
    '',
    '> ' + runs + '회 실행 · ' + new Date().toLocaleString('ko-KR'),
    '',
    '## 생존 시간 통계',
    '',
    '| 항목 | 값 |',
    '|------|----|',
    '| 평균 | ' + mean.toFixed(1) + 's |',
    '| 중앙값 | ' + median.toFixed(1) + 's |',
    '| 표준편차 | ' + stddev.toFixed(1) + 's |',
    '| p25 / p75 | ' + p25.toFixed(1) + 's / ' + p75.toFixed(1) + 's |',
    '| p90 / p95 | ' + p90.toFixed(1) + 's / ' + p95.toFixed(1) + 's |',
    '| 타임아웃 | ' + (timeoutRate * 100).toFixed(0) + '% |',
    '',
    '## 점수',
    '',
    '평균 **' + Math.round(scoreMean) + '** · 최고 **' + scoreMax + '**',
    levelSection,
    deathPatternSection,
    '## 분포 히스토그램',
    '',
    '```',
    histLines,
    '```',
    '',
    '> 💡 ' + advice,
    '',
    suggestionsSection,
    '---',
    '_Generated by [radar_fun_meter](https://github.com/on1659/radar_fun_meter)_',
    '',
  ];

  return lines.join('\n');
}

module.exports = { toMarkdown };
